// Settings
export const SETTINGS_TOGGLE_HEADER_MENU = 'SETTINGS_TOGGLE_HEADER_MENU';
export const SETTINGS_GET_WEATHER = 'SETTINGS_GET_WEATHER';

// Auth
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_DELETE_USER = 'AUTH_DELETE_USER';

// Chat
export const CHAT_ADD_ROOM = 'CHAT_ADD_ROOM';
export const CHAT_GET_ROOMS = 'CHAT_GET_ROOMS';
export const CHAT_GET_ROOM = 'CHAT_GET_ROOM';
export const CHAT_SET_SELECTED_ROOM = 'CHAT_SET_SELECTED_ROOM';
export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE';
export const CHAT_DISCONNECT = 'CHAT_DISCONNECT';